In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os as os
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
import lightgbm as lgb
import scipy as sp
from sklearn.preprocessing import MinMaxScaler
from scipy.special import boxcox1p
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import uniform
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score
from sklearn.metrics import f1_score, confusion_matrix, precision_recall_curve, roc_curve
from imblearn.under_sampling import *
from imblearn.over_sampling import *
from imblearn.combine import *
import tensorflow as tf
plt.style.use('seaborn')

/usr/local/lib/python3.6/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np

In [2]:
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense
from keras.callbacks import EarlyStopping
from keras.callbacks import ModelCheckpoint
from keras import backend as K

Using TensorFlow backend.


In [18]:
!pip install --upgrade tensorflow==1.14.0

     |████████████████████████████████| 109.2MB 100kB/s 
     |████████████████████████████████| 491kB 44.0MB/s 
     |████████████████████████████████| 3.2MB 41.1MB/s 
  Found existing installation: tensorflow-estimator 1.15.1
    Uninstalling tensorflow-estimator-1.15.1:
      Successfully uninstalled tensorflow-estimator-1.15.1
  Found existing installation: tensorboard 1.15.0
    Uninstalling tensorboard-1.15.0:
      Successfully uninstalled tensorboard-1.15.0
  Found existing installation: tensorflow 1.15.0
    Uninstalling tensorflow-1.15.0:
      Successfully uninstalled tensorflow-1.15.0


In [3]:
from __future__ import absolute_import, division, print_function, unicode_literals

!pip install tensorflow-gpu==2.0.0-rc1
import tensorflow as tf

     |████████████████████████████████| 380.5MB 43kB/s 
     |████████████████████████████████| 501kB 9.2MB/s 
     |████████████████████████████████| 4.3MB 62.6MB/s 


In [3]:
tf.__version__

'1.14.0'

In [0]:
import matplotlib.ticker as ticker
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import RadiusNeighborsClassifier
from sklearn.neighbors import KNeighborsClassifier
from datetime import tzinfo, timedelta, datetime
from sklearn import metrics
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler

from keras.layers.advanced_activations import PReLU
from keras.layers.core import Dense, Dropout, Activation
from keras.layers.normalization import BatchNormalization
from keras.models import Sequential
from keras.utils import np_utils

In [0]:
train = pd.read_csv('/content/drive/My Drive/Colab Notebooks/train.csv')
test = pd.read_csv('/content/drive/My Drive/Colab Notebooks/test.csv')
sample_submission = pd.read_csv('/content/drive/My Drive/Colab Notebooks/sample_submission.csv')

In [0]:
le = LabelEncoder()
train_y = le.fit_transform(train['type'])

In [7]:
train_x=train.drop(columns=['id','type'])
train_x

fiberID   psfMag_u   psfMag_g  ...  modelMag_r  modelMag_i  modelMag_z
0           601  23.198224  21.431953  ...   21.364187   21.020605   21.147340
1           788  21.431355  20.708104  ...   20.753925   20.693389   20.512314
2           427  17.851451  16.727898  ...   16.641249   16.660177   16.688928
3           864  20.789900  20.040371  ...   19.889798   19.758113   19.552855
4           612  26.454969  23.058767  ...   21.475342   19.487330   18.375655
...         ...        ...        ...  ...         ...         ...         ...
199986      568  20.630780  20.437920  ...   20.014046   20.061940   19.862513
199987      362  25.283695  22.807243  ...   19.776321   18.990039   18.528306
199988      146  23.609826  21.902709  ...   20.420524   18.443126   17.331724
199989       85  21.172003  20.561208  ...   17.440331   17.193743   16.969854
199990      964  20.624498  20.122276  ...   20.327396   20.217198   19.995023

[199991 rows x 21 columns]

In [0]:
test_id=test['id']
test=test.drop(columns='id')

In [9]:
ro_train_x, ro_train_y = RandomOverSampler(random_state=0).fit_sample(train_x, train_y)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [10]:
ro_X_train=pd.DataFrame(ro_train_x)
ro_X_train.columns=['fiberID', 'psfMag_u', 'psfMag_g', 'psfMag_r', 'psfMag_i', 'psfMag_z', 'fiberMag_u','fiberMag_g', 'fiberMag_r', 'fiberMag_i', 'fiberMag_z','petroMag_u', 'petroMag_g', 'petroMag_r', 'petroMag_i', 'petroMag_z', 'modelMag_u', 'modelMag_g', 'modelMag_r', 'modelMag_i', 'modelMag_z']
ro_X_train

fiberID   psfMag_u   psfMag_g  ...  modelMag_r  modelMag_i  modelMag_z
0         601.0  23.198224  21.431953  ...   21.364187   21.020605   21.147340
1         788.0  21.431355  20.708104  ...   20.753925   20.693389   20.512314
2         427.0  17.851451  16.727898  ...   16.641249   16.660177   16.688928
3         864.0  20.789900  20.040371  ...   19.889798   19.758113   19.552855
4         612.0  26.454969  23.058767  ...   21.475342   19.487330   18.375655
...         ...        ...        ...  ...         ...         ...         ...
943915    422.0  18.924247  19.424055  ...   19.949122   20.217886   20.632650
943916    460.0  20.852332  19.350697  ...   18.777714   18.566403   18.442977
943917    251.0  18.909815  18.786982  ...   19.123858   19.488318   19.502875
943918    260.0  20.341070  19.323051  ...   18.935578   18.762227   18.761944
943919    340.0  19.878536  19.678007  ...   19.320526   19.323561   19.152396

[943920 rows x 21 columns]

In [11]:
# convert integers to dummy variables (i.e. one hot encoded)
ro_y_train= np_utils.to_categorical(ro_train_y)
print(ro_y_train)

[[0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [12]:
input_dim = ro_X_train.shape[1]
output_dim = len(ro_y_train)
print('Input dimensions: {}'.format(input_dim))
print('output dimensios:{}'.format(output_dim))

Input dimensions: 21
output dimensios:943920


In [0]:
from sklearn.model_selection import train_test_split
ro_X_train, ro_X_valid, ro_y_train, ro_y_valid = train_test_split(ro_train_x, ro_train_y, \
                                                  test_size=0.2, random_state=42, stratify = ro_train_y)

In [14]:
ro_X_train=pd.DataFrame(ro_X_train)
ro_X_train.columns=['fiberID', 'psfMag_u', 'psfMag_g', 'psfMag_r', 'psfMag_i', 'psfMag_z','fiberMag_u','fiberMag_g', 'fiberMag_r', 'fiberMag_i', 'fiberMag_z','petroMag_u', 'petroMag_g', 'petroMag_r', 'petroMag_i', 'petroMag_z', 'modelMag_u', 'modelMag_g', 'modelMag_r', 'modelMag_i', 'modelMag_z']
ro_X_train


fiberID   psfMag_u   psfMag_g  ...  modelMag_r  modelMag_i  modelMag_z
0         188.0  19.953053  19.513746  ...   19.717623   19.923045   20.051332
1         109.0  20.078130  19.117335  ...   18.742305   18.552699   18.577980
2         601.0  24.448046  21.002730  ...   19.440860   17.998810   17.254946
3         394.0  21.667405  19.466610  ...   17.972276   16.903080   16.317867
4         354.0  17.825027  16.837443  ...   17.078484   17.278744   17.408630
...         ...        ...        ...  ...         ...         ...         ...
755131    636.0  16.901155  16.027993  ...   15.627033   15.492005   15.460698
755132    402.0  18.839897  18.830066  ...   19.172067   19.455918   19.754953
755133     37.0  22.662867  20.937430  ...   19.437572   18.054282   17.352494
755134    381.0  18.262031  17.831090  ...   18.078614   18.327034   18.578339
755135    614.0  20.834914  20.335761  ...   20.562302   22.004985   20.845734

[755136 rows x 21 columns]

In [0]:
ro_X_valid=pd.DataFrame(ro_X_valid)
ro_X_valid.columns=['fiberID', 'psfMag_u', 'psfMag_g', 'psfMag_r', 'psfMag_i', 'psfMag_z','fiberMag_u','fiberMag_g', 'fiberMag_r', 'fiberMag_i', 'fiberMag_z','petroMag_u', 'petroMag_g', 'petroMag_r', 'petroMag_i', 'petroMag_z', 'modelMag_u', 'modelMag_g', 'modelMag_r', 'modelMag_i', 'modelMag_z']

In [0]:
def recall_m(y_true, y_pred):
        true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
        possible_positives = K.sum(K.round(K.clip(y_true, 0, 1)))
        recall = true_positives / (possible_positives + K.epsilon())
        return recall

def precision_m(y_true, y_pred):
        true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
        predicted_positives = K.sum(K.round(K.clip(y_pred, 0, 1)))
        precision = true_positives / (predicted_positives + K.epsilon())
        return precision

def f1_m(y_true, y_pred):
    precision = precision_m(y_true, y_pred)
    recall = recall_m(y_true, y_pred)
    return 2*((precision*recall)/(precision+recall+K.epsilon()))

In [21]:
print(ro_X_train.shape)
print(ro_X_valid.shape)
print(test)

(755136, 21)
(188784, 21)
       fiberID   psfMag_u   psfMag_g  ...  modelMag_r  modelMag_i  modelMag_z
0          251  23.817399  22.508963  ...   21.011918   18.499341   17.091474
1          386  22.806983  21.937111  ...   20.173169   19.796757   19.567372
2          232  21.024250  19.235669  ...   17.562108   17.120529   16.708748
3          557  20.503424  20.286261  ...   20.150499   20.206221   20.092909
4           75  24.244851  22.668237  ...   21.191862   19.237964   18.280368
...        ...        ...        ...  ...         ...         ...         ...
10004      389  19.765035  19.542406  ...   19.432463   19.376445   19.354976
10005      247  19.960030  19.609379  ...   19.334113   19.401240   19.159412
10006      941  21.221899  20.276182  ...   20.141549   19.906014   19.953932
10007      674  21.625469  21.624585  ...   21.128330   21.430526   21.220902
10008      358  17.438361  16.531405  ...   16.176274   16.045822   15.995814

[10009 rows x 21 columns]


In [0]:
#3. 모델 구성하기
model = Sequential()
model.add(Dense(76, input_dim= ro_X_train.shape[1], activation ='relu'))
model.add(Dense(76, activation ='relu'))
model.add(Dense(38, activation ='relu'))
model.add(Dense(38, activation ='relu'))
model.add(Dense(19, activation ='softmax'))

#4. 모델 학습과정 설정하기
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['acc',f1_m,precision_m, recall_m])



#5. 모델 학습시키기
#5.1. Early Stopping
callbacks_list = [
    EarlyStopping(
    monitor='val_acc',
    patience=10,
    ),
     ModelCheckpoint(
     filepath='multi_model.h5',
     monitor='val_loss',
     save_best_only=True,
     )
]

hist = model.fit(ro_X_train, ro_y_train, epochs = 100,callbacks=callbacks_list,validation_data=(ro_X_valid, ro_y_valid))

#6. 모델 평가하기
scores = model.evaluate(ro_X_valid, ro_y_valid)
print("%s: %.2f%%" %(model.metrics_names[1], scores[1]*100))

Train on 755136 samples, validate on 188784 samples
Epoch 1/100
755136/755136 [==============================] - 39s 52us/step - loss: 1.4543 - acc: 0.4756 - f1_m: 5.5570 - precision_m: 186293762.8951 - recall_m: 3.6128 - val_loss: 1.1048 - val_acc: 0.6024 - val_f1_m: 3.8230 - val_precision_m: 5.5730 - val_recall_m: 2.9465
Epoch 2/100
755136/755136 [==============================] - 40s 53us/step - loss: 1.0061 - acc: 0.6403 - f1_m: 3.1677 - precision_m: 3.9781 - recall_m: 2.6626 - val_loss: 0.8946 - val_acc: 0.6904 - val_f1_m: 2.8715 - val_precision_m: 3.3447 - val_recall_m: 2.5330
Epoch 3/100
755136/755136 [==============================] - 38s 50us/step - loss: 0.8861 - acc: 0.6840 - f1_m: 2.7102 - precision_m: 3.1256 - recall_m: 2.4093 - val_loss: 0.7979 - val_acc: 0.7205 - val_f1_m: 2.4702 - val_precision_m: 2.7106 - val_recall_m: 2.2799
Epoch 4/100
687840/755136 [==========================>...] - ETA: 2s - loss: 0.8261 - acc: 0.7042 - f1_m: 2.5000 - precision_m: 2.7918 - recall_m

In [0]:
#epoch, loss, acc 그래프
loss = hist.history['loss']
val_loss = hist.history['val_loss']
acc = hist.history['acc']
val_acc = hist.history['val_acc']

epochs = range(1, len(loss)+1)
plt.plot(epochs, loss, 'b', label='Training loss')
plt.plot(epochs, val_loss, 'g', label='Validation loss')
plt.plot(epochs, acc, 'y', label='Training accuracy')
plt.plot(epochs, val_acc, 'r', label='Validation accuracy')

plt.title('Training/Validation loss and accuracy')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()


In [0]:
def base_model():
    # create model
    model = Sequential()
    model.add(Dense(256, input_dim=21, init='normal', activation='relu'))
    model.add(Dropout(0.2))
    model.add(Dense(128, init='normal', activation='relu'))
    model.add(Dropout(0.2))
    
    model.add(Dense(19, init='normal', activation='softmax'))
    # Compile model
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

In [0]:
estimator = KerasClassifier(build_fn=base_model, nb_epoch=30, batch_size=5, verbose=0)
kfold = KFold(n_splits=2, shuffle=True)
split = ShuffleSplit(n_splits=2, train_size=0.8)
estimator.fit(ro_X_train, ro_y_train)
results = cross_val_score(estimator, ro_X_train, ro_y_train, cv=split)
print("Base model: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(256, input_dim=21, activation="relu", kernel_initializer="normal")`
  after removing the cwd from sys.path.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(128, activation="relu", kernel_initializer="normal")`
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(19, activation="softmax", kernel_initializer="normal")`
  if __name__ == '__main__':


In [0]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [0]:
model.fit(x_train, y_train, epochs=5)

model.evaluate(x_test,  y_test, verbose=2)

In [0]:
def build_model(input_dim, output_dim, hn=64, dp=0.5, layers=3):
    model = Sequential()
    model.add(Dense(output_dim, input_shape=(input_dim,)))
    model.add(PReLU())
    
    model.add(Dense(output_dim, kernel_regularizer=regularizers.l2(0.01),
                activity_regularizer=regularizers.l1(0.01)))
    model.add(PReLU())

    model.add(Dense(output_dim, activation='softmax'))

    model.compile(loss='categorical_crossentropy', optimizer='nadam')
    return model

In [0]:
print("Generating submission...")

model = tf.keras.models.Sequential()
model.add(Dense(100, input_shape=input_dim))
model.add(PReLU())
    
model.add(Dense(100, kernel_regularizer=regularizers.l2(0.01), activity_regularizer=regularizers.l1(0.01)))
model.add(PReLU())

model.add(Dense(output_dim=19, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='nadam')

model.fit(X, Y, nb_epoch=EPOCHS, batch_size=BATCHES, verbose=0)

In [0]:
model = tf.keras.models.Sequential()


RuntimeError: ignored